name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'  # or whichever version you are using

      - name: Install dependencies
        run: flutter pub get
        working-directory: HeartLens

      - name: Build Flutter APK
        run: flutter build apk --release
        working-directory: HeartLens

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: HeartLens
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
